[package]
name = "fast-btr-parser-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.3"
serde_json = "1.0.114"

[lib]
name = "fast_btr_parser"
path = "src/lib.rs"
